#!/usr/bin/env bash
#
# Wizard migrasi storage media → Supabase Storage (S3-compatible)
# untuk portfolio-backend-api. Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.storage-wizard.local}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

BACKEND_API="https://portfolio-backend-api-five.vercel.app/api/v1"
ADMIN_URL="https://kadekagga-portfolio.vercel.app/admin/login"
DEAD_REF="nfwdysmbihywkowmcsfj"

banner "Migrasi storage media → Supabase Storage baru"

# Helper: set one env var pada proyek Vercel backend (production + preview).
vercel_set() {
  local name="$1" value="$2" e
  command -v vercel >/dev/null 2>&1 || { warn "vercel CLI tidak ada — set $name manual di dashboard"; SKIPPED+=("Vercel env $name"); return; }
  for e in production preview; do
    vercel env rm "$name" "$e" --yes >/dev/null 2>&1 || true
    if printf '%s' "$value" | vercel env add "$name" "$e" >/dev/null 2>&1; then
      printf '  %s✓%s %s → Vercel (%s)\n' "$GREEN" "$RESET" "$name" "$e"
    else
      warn "gagal set $name ($e) — set manual di dashboard Vercel"
      SKIPPED+=("Vercel env $name ($e)")
    fi
  done
}

# ── Stage 1: pulihkan file asli ───────────────────────────────────────────
stage "Pulihkan file asli (7 media hilang)"
say "Proyek Supabase lama ($DEAD_REF) sudah terhapus dan tidak diarsipkan"
say "Wayback Machine. File berikut harus dicari/dibuat ulang:"
say ""
note "  1. WhatsApp Image 2026-07-27 at 16.12.02.jpeg  ← FOTO PROFIL (hero)"
note "     → cari di folder WhatsApp Media/Downloads laptop ini"
note "  2. CV PDF (oGDjRbZ0…pdf)"
note "     → cari file CV terakhir yang pernah di-upload"
note "  3-7. Lima gambar proyek (*.png)"
note "     → screenshot/aset folder proyek di laptop"
pause "Sudah siap/kumpulkan file-filenya?"

# ── Stage 2: proyek Supabase baru ────────────────────────────────────────
stage "Supabase — buat proyek baru (gratis, tanpa kartu)"
open_url "https://supabase.com/dashboard"
step "Login → 'New project'. Nama bebas (mis. portfolio-storage)."
step "Database Password: isi saja (tidak akan dipakai untuk storage)."
step "Region: Singapore (ap-southeast-1) — dekat dengan backend sin1."
step "Tunggu provisioning selesai (~2 menit)."
step "Buka Project Settings → API (atau halaman Home), salin Project URL"
step "(bentuknya https://<ref>.supabase.co — <ref> HARUS berbeda dari lama)."
ask SUPABASE_PROJECT_URL "Paste Project URL:"
SUPABASE_PROJECT_URL="${SUPABASE_PROJECT_URL%/}"
write_env SUPABASE_PROJECT_URL "$SUPABASE_PROJECT_URL"

# ── Stage 3: bucket public ────────────────────────────────────────────────
stage "Supabase — buat bucket public 'portfolio-media'"
step "Di sidebar proyek: Storage → 'New bucket'."
step "Name: portfolio-media — centang/hidupkan 'Public bucket'."
step "Klik Create. Tidak perlu RLS policy tambahan untuk baca publik."
pause "Bucket sudah dibuat?"

# ── Stage 4: kredensial S3 ────────────────────────────────────────────────
stage "Supabase — buat S3 access key"
step "Masih di Storage: buka tab/gear Settings → bagian 'S3 access keys'"
step "(bila tidak ketemu, panduan resmi: supabase.com/docs/guides/storage/s3)."
step "'Create new access key' → salin Access Key ID dan Secret Access Key."
step "Catat juga region proyek (mis. ap-southeast-1)."
ask SUPABASE_REGION "Paste region proyek (mis. ap-southeast-1):"
ask SUPABASE_S3_ACCESS_KEY_ID "Paste Access Key ID:"
ask_secret SUPABASE_S3_SECRET_ACCESS_KEY "Paste Secret Access Key:"
write_env SUPABASE_REGION "$SUPABASE_REGION"
write_env SUPABASE_S3_ACCESS_KEY_ID "$SUPABASE_S3_ACCESS_KEY_ID"
write_env SUPABASE_S3_SECRET_ACCESS_KEY "$SUPABASE_S3_SECRET_ACCESS_KEY"

# ── Stage 5: pasang env di Vercel ─────────────────────────────────────────
stage "Vercel — pasang env storage baru (portfolio-backend-api)"
say "Akan menimpa MEDIA_DISK + seluruh AWS_* di environment production"
say "dan preview milik proyek portfolio-backend-api via Vercel CLI:"
note "  MEDIA_DISK=s3"
note "  AWS_BUCKET=portfolio-media"
note "  AWS_DEFAULT_REGION=$SUPABASE_REGION"
note "  AWS_ENDPOINT=$SUPABASE_PROJECT_URL/storage/v1/s3"
note "  AWS_URL=$SUPABASE_PROJECT_URL/storage/v1/object/public/portfolio-media"
note "  AWS_USE_PATH_STYLE_ENDPOINT=true"
note "  (+ kredensial S3 key/secret)"
if confirm "Lanjut timpa env di Vercel?"; then
  vercel_set MEDIA_DISK                  "s3"
  vercel_set AWS_BUCKET                  "portfolio-media"
  vercel_set AWS_DEFAULT_REGION          "$SUPABASE_REGION"
  vercel_set AWS_ENDPOINT                "$SUPABASE_PROJECT_URL/storage/v1/s3"
  vercel_set AWS_URL                     "$SUPABASE_PROJECT_URL/storage/v1/object/public/portfolio-media"
  vercel_set AWS_USE_PATH_STYLE_ENDPOINT "true"
  vercel_set AWS_ACCESS_KEY_ID           "$SUPABASE_S3_ACCESS_KEY_ID"
  vercel_set AWS_SECRET_ACCESS_KEY       "$SUPABASE_S3_SECRET_ACCESS_KEY"
else
  note "Dilewati. Set manual nanti di vercel.com → project → Settings → Environment Variables."
fi

# ── Stage 6: deploy ulang backend ─────────────────────────────────────────
stage "Deploy ulang backend"
say "Env baru hanya aktif setelah redeploy. Deploy dari CLI memakai working"
say "tree lokal — termasuk perbaikan kode resolusi URL yang belum di-commit."
if confirm "Deploy sekarang (cd backend && vercel --prod)?"; then
  if ( cd backend && vercel --prod --yes ); then
    step "Menunggu API hidup kembali…"
    sleep 10
    if curl -sf --max-time 60 "$BACKEND_API/health" >/dev/null 2>&1; then
      printf '  %s✓ health UP%s\n' "$GREEN" "$RESET"
    else
      warn "health belum merespons — cek dashboard Vercel deployments"
    fi
  else
    warn "deploy gagal — jalankan manual: cd backend && vercel --prod"
  fi
else
  note "Dilewati. Alternatif: commit + push ke git (jalankan wizard lagi untuk verifikasi)."
fi

# ── Stage 7: upload ulang media + verifikasi akhir ────────────────────────
stage "Upload ulang media lewat admin panel"
open_url "$ADMIN_URL"
step "Login admin → menu Media → upload 7 file dari Stage 1."
step "Buka Profil → pilih foto profil yang baru di-upload → simpan."
step "Buka tiap Proyek → attach gambar yang sesuai."
step "Simpan juga CV di kolom cv (Profil) bila berlaku."
pause "Selesai upload?"
say "Verifikasi respons API:"
PHOTO=$(curl -sf --max-time 30 "$BACKEND_API/profile" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['data'][0].get('photo') or '')" 2>/dev/null || true)
if [[ -z "$PHOTO" ]]; then
  warn "tidak bisa membaca photo dari $BACKEND_API/profile"
elif [[ "$PHOTO" == *"$DEAD_REF"* ]]; then
  warn "photo masih menunjuk proyek Supabase LAMA: $PHOTO"
  note "→ foto profil belum diganti di admin panel."
else
  printf '  %s✓ photo baru:%s %s\n' "$GREEN" "$RESET" "$PHOTO"
  CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$PHOTO" || echo 000)
  if [[ "$CODE" == "200" ]]; then
    printf '  %s✓ gambar HTTP 200 — masalah beres%s\n' "$GREEN" "$RESET"
  else
    warn "gambar HTTP $CODE — cek bucket sudah 'Public' dan nama bucket benar"
  fi
fi
say ""
warn "Ingat: proyek Supabase gratis bisa di-pause jika lama tidak aktif."
note "Sesekali buka dashboard, atau upgrade pay-as-you-go bila sudah serius."
